"use client";

import { useCallback, useEffect, useMemo, useState, useTransition } from "react";
import { Boxes, ClipboardPlus, Loader2, PackageCheck, Plus, Truck } from "lucide-react";
import { createAgencyBoxRequestAction, listAgencyRequestCustomersAction, listAgencyRequestsAction, loadAgencyBoxInventoryAction, loadAgencyDeliveryCatalogAction, type AgencyBoxBalance, type AgencyBoxCatalogItem, type AgencyRequest, type AgencyRequestCustomer, type AgencyServiceCode } from "@/app/actions/agency-operations";
import { useNotify } from "@/hooks/use-notify";
import { Panel, inputClass, primaryButtonClass, secondaryButtonClass } from "@/components/ui-blocks";

type RequestDraft = { serviceCode: AgencyServiceCode; inventoryItemId: string; warehouseId: string; productKey: string; boxSize: string; quantity: string; customerId: string };
const labels: Record<AgencyServiceCode,string> = { agency_office_empty_box_delivery:"Llevar cajas vacías a la agencia", agency_office_full_box_pickup:"Recoger cajas llenas en la agencia", customer_home_delivery:"Realizar domicilio para un cliente", customer_empty_box_delivery:"Entregar caja vacía al cliente", customer_full_box_pickup:"Recoger caja llena del cliente" };
const statusLabel: Record<string,string> = { submitted:"Enviada",under_review:"En revisión",confirmed:"Confirmada",scheduled:"Programada",assigned:"Asignada",in_route:"En ruta",completed:"Completada",partially_completed:"Atendida parcialmente" };
const emptyDraft = (): RequestDraft => ({ serviceCode:"agency_office_empty_box_delivery",inventoryItemId:"",warehouseId:"",productKey:"",boxSize:"",quantity:"1",customerId:"" });
const isCustomerService=(code:AgencyServiceCode)=>code.startsWith("customer_");
const needsEmptyBox=(code:AgencyServiceCode)=>code==="agency_office_empty_box_delivery"||code==="customer_empty_box_delivery";
const needsAgencyBox=(code:AgencyServiceCode)=>code==="agency_office_full_box_pickup"||code==="customer_full_box_pickup";

export function AgencyOperationsPanel({ canRequest=false }:{canRequest?:boolean}) {
  const notify=useNotify(); const [inventory,setInventory]=useState<AgencyBoxBalance[]>([]); const [deliveryCatalog,setDeliveryCatalog]=useState<AgencyBoxCatalogItem[]>([]); const [customers,setCustomers]=useState<AgencyRequestCustomer[]>([]); const [requests,setRequests]=useState<AgencyRequest[]>([]); const [open,setOpen]=useState(false); const [pending,startTransition]=useTransition(); const [draft,setDraft]=useState<RequestDraft>(emptyDraft); const [lines,setLines]=useState<RequestDraft[]>([]); const [note,setNote]=useState("");
  const available=useMemo(()=>inventory.reduce((total,item)=>total+item.availableQuantity,0),[inventory]);
  const reload=useCallback(async()=>{const [inventoryResult,requestsResult,catalogResult,customersResult]=await Promise.all([loadAgencyBoxInventoryAction(),listAgencyRequestsAction(),loadAgencyDeliveryCatalogAction(),listAgencyRequestCustomersAction()]);if(inventoryResult.ok)setInventory(inventoryResult.data);if(requestsResult.ok)setRequests(requestsResult.data);if(catalogResult.ok)setDeliveryCatalog(catalogResult.data);if(customersResult.ok)setCustomers(customersResult.data);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void reload();},0);return()=>window.clearTimeout(timer);},[reload]);
  const selectedCustomer=customers.find((customer)=>customer.id===draft.customerId)||null;
  function chooseBox(value:string){const selected=needsEmptyBox(draft.serviceCode)?deliveryCatalog.find((item)=>`${item.inventoryItemId}:${item.warehouseId}`===value):inventory.find((item)=>item.inventoryItemId===value);setDraft((current)=>({...current,inventoryItemId:selected?.inventoryItemId||"",warehouseId:"warehouseId" in (selected||{})?(selected as AgencyBoxCatalogItem).warehouseId||"":"",productKey:selected?.productKey||"",boxSize:selected?.boxSize||""}));}
  function lineComplete(line:RequestDraft){return Number.isSafeInteger(Number(line.quantity))&&Number(line.quantity)>0&&(!isCustomerService(line.serviceCode)||Boolean(line.customerId))&&(!(needsEmptyBox(line.serviceCode)||needsAgencyBox(line.serviceCode))||Boolean(line.inventoryItemId));}
  function addLine(){if(!lineComplete(draft))return notify.error("Completa el servicio, cliente, caja y cantidad requeridos.");const expectedScope=isCustomerService(lines[0]?.serviceCode||draft.serviceCode);if(lines.length&&expectedScope!==isCustomerService(draft.serviceCode))return notify.error("Separa los servicios de oficina y cliente en solicitudes distintas.");if(lines.length&&isCustomerService(draft.serviceCode)&&lines[0].customerId!==draft.customerId)return notify.error("Cada solicitud a domicilio corresponde a un solo cliente.");setLines((current)=>[...current,draft]);setDraft({...emptyDraft(),serviceCode:draft.serviceCode,customerId:draft.customerId});}
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const requestLines=[...lines,...(lineComplete(draft)?[draft]:[])];if(!requestLines.length)return notify.error("Agrega al menos un servicio válido.");startTransition(async()=>{const result=await createAgencyBoxRequestAction({lines:requestLines.map((line)=>{const customer=customers.find((item)=>item.id===line.customerId);return{serviceCode:line.serviceCode,quantity:Number(line.quantity),productKey:line.productKey,boxSize:line.boxSize,inventoryItemId:line.inventoryItemId,warehouseId:line.warehouseId,customerId:customer?.id,destinationCode:customer?.destinationCode,address:customer?.address};}),note});if(!result.ok)return notify.error(result.error);notify.success("Solicitud operativa enviada a logística.");setOpen(false);setDraft(emptyDraft());setLines([]);setNote("");await reload();});}
  return <div className="space-y-4"><Panel title="Cajas de mi agencia" action={<span className="rounded-md bg-emerald-400/10 px-2 py-1 text-xs font-black text-emerald-200">{available} disponibles</span>}><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{inventory.length?inventory.map((item)=><article key={item.id} className="rounded-lg border border-black bg-surface-list-row p-3"><p className="truncate text-sm font-black text-slate-100">{item.productKey||"Caja"}</p><p className="text-xs font-bold text-slate-400">{item.boxSize||"Sin tamaño"}</p><p className="mt-3 text-2xl font-black text-emerald-200">{item.availableQuantity}</p><p className="text-xs font-bold text-slate-500">{item.allocatedQuantity} usadas de {item.deliveredQuantity}</p></article>):<p className="rounded-lg border border-dashed border-slate-700 px-3 py-6 text-sm font-bold text-slate-400 sm:col-span-2 xl:col-span-4">Todavía no hay cajas confirmadas en la agencia.</p>}</div></Panel>
  <Panel title="Solicitudes logísticas" action={canRequest?<button type="button" className={primaryButtonClass} onClick={()=>setOpen((value)=>!value)}><ClipboardPlus className="h-4 w-4"/> Nueva solicitud</button>:<Boxes className="h-5 w-5 text-emerald-300"/>}>{open?<form className="mb-3 grid gap-2 rounded-lg border border-black bg-surface-inset p-3 sm:grid-cols-2" onSubmit={submit}>{lines.length?<div className="grid gap-1 sm:col-span-2">{lines.map((line,index)=><div key={`${line.serviceCode}-${index}`} className="flex items-center justify-between rounded-md bg-surface-card px-3 py-2 text-sm font-bold text-slate-200"><span>{labels[line.serviceCode]} · {line.quantity}</span><button type="button" className="text-xs text-rose-200" onClick={()=>setLines((current)=>current.filter((_,currentIndex)=>currentIndex!==index))}>Quitar</button></div>)}</div>:null}
  <label className="grid gap-1 text-xs font-black text-slate-300 sm:col-span-2">Servicio<select className={inputClass} value={draft.serviceCode} onChange={(event)=>setDraft({...emptyDraft(),serviceCode:event.target.value as AgencyServiceCode})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
  {isCustomerService(draft.serviceCode)?<label className="grid gap-1 text-xs font-black text-slate-300 sm:col-span-2">Cliente de la agencia<select className={inputClass} required value={draft.customerId} onChange={(event)=>setDraft((current)=>({...current,customerId:event.target.value}))}><option value="">Selecciona el cliente y su domicilio</option>{customers.map((customer)=><option key={customer.id} value={customer.id}>{customer.name} · {customer.addressLabel||"Sin dirección"}</option>)}</select>{selectedCustomer&&!selectedCustomer.addressLabel?<span className="text-amber-200">Este cliente necesita una dirección antes de solicitar el servicio.</span>:null}</label>:null}
  <label className="grid gap-1 text-xs font-black text-slate-300">Cantidad<input className={inputClass} type="number" min="1" inputMode="numeric" value={draft.quantity} onChange={(event)=>setDraft((current)=>({...current,quantity:event.target.value}))}/></label>
  {needsEmptyBox(draft.serviceCode)||needsAgencyBox(draft.serviceCode)?<label className="grid gap-1 text-xs font-black text-slate-300">Tipo de caja<select className={inputClass} required value={needsEmptyBox(draft.serviceCode)?`${draft.inventoryItemId}:${draft.warehouseId}`:draft.inventoryItemId} onChange={(event)=>chooseBox(event.target.value)}><option value="">Selecciona una caja</option>{needsEmptyBox(draft.serviceCode)?deliveryCatalog.map((item)=><option key={`${item.inventoryItemId}:${item.warehouseId}`} value={`${item.inventoryItemId}:${item.warehouseId}`}>{item.label} ({item.availableQuantity})</option>):inventory.map((item)=><option key={item.id} value={item.inventoryItemId}>{item.productKey} · {item.boxSize} ({item.availableQuantity})</option>)}</select></label>:<div/>}
  <button type="button" className={`${secondaryButtonClass} w-fit sm:col-span-2`} onClick={addLine}><Plus className="h-4 w-4"/> Agregar otro servicio</button><label className="grid gap-1 text-xs font-black text-slate-300 sm:col-span-2">Nota<input className={inputClass} value={note} onChange={(event)=>setNote(event.target.value)} placeholder="Horario o indicación operativa"/></label><div className="flex gap-2 sm:col-span-2"><button className={primaryButtonClass} disabled={pending}>{pending?<Loader2 className="h-4 w-4 animate-spin"/>:<PackageCheck className="h-4 w-4"/>} Enviar solicitud</button><button type="button" className={secondaryButtonClass} onClick={()=>setOpen(false)}>Cancelar</button></div></form>:null}
  <div className="grid gap-2">{requests.length?requests.map((request)=><article key={request.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-black bg-surface-list-row p-3"><Truck className="h-4 w-4 text-emerald-300"/><div className="min-w-0 flex-1"><p className="font-black text-slate-100">{request.code} · {request.requestScope==="agency_customer"?"Cliente de agencia":"Oficina"}</p><p className="text-xs font-bold text-slate-400">{request.lines.map((line)=>`${labels[line.serviceCode]} ${line.requestedQuantity}${line.unitChargeAmountCents?` · cargo aplicado $${(line.unitChargeAmountCents/100).toFixed(2)}`:""}`).join(" · ")}</p>{request.address?<p className="text-xs font-bold text-slate-500">{request.address}</p>:null}</div><span className="text-xs font-black text-amber-200">{statusLabel[request.status]||request.status}</span></article>):<p className="rounded-lg border border-dashed border-slate-700 px-3 py-6 text-sm font-bold text-slate-400">No hay solicitudes abiertas.</p>}</div></Panel></div>;
}
